import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('zh');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'zh';
    setLanguage(savedLanguage);
  }, []);

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key) => {
    const translations = {
      zh: {
        dashboardTitle: '统一监控仪表盘',
        loading: '加载中...',
        loadError: '加载数据失败',
        retry: '重试',
        noData: '暂无数据',
        cloudflare: 'Cloudflare',
        edgeone: 'EdgeOne',
        unified: '统一视图',
        totalRequests: '总请求数',
        totalTraffic: '总流量',
        totalBandwidth: '总带宽',
        totalThreats: '总威胁数',
        cachedRequests: '缓存请求数',
        cachedBytes: '缓存流量',
        cacheHitRate: '缓存命中率',
        geography: '地理位置',
        traffic: '流量',
        bandwidth: '带宽',
        originPull: '回源分析',
        requests: '请求数',
        bytes: '流量',
        threats: '威胁',
        country: '国家/地区',
        last24Hours: '最近24小时',
        last7Days: '最近7天',
        last30Days: '最近30天',
        period: '时间范围',
        account: '账户',
        zone: '站点',
        platform: '平台',
        autoRefresh: '自动刷新',
        refresh: '刷新',
        customRange: '自定义范围',
        apply: '应用',
        topUrls: '热门 URL',
        topReferers: '热门来源',
        topBrowsers: '热门浏览器',
        topOS: '热门操作系统',
        topDevices: '设备类型分布',
        count: '请求数',
        ratio: '占比',
        item: '项目',
        statusCodeDistribution: '状态码分布',
        securityStats: '安全统计',
        intercepts: '拦截次数',
        edgeFunctions: '边缘函数',
        functionRequests: '函数请求数',
        cpuTime: 'CPU 时间',
        trafficAnalysis: '流量分析',
        bandwidthAnalysis: '带宽分析',
        clientRequestTraffic: '客户端请求流量',
        responseTraffic: '响应流量',
        peakBandwidth: '总带宽峰值',
        peakRequestBandwidth: '请求带宽峰值',
        peakResponseBandwidth: '响应带宽峰值',
        clientRequests: '客户端请求',
        response: '响应',
        trafficTotal: '总流量',
        trafficRequest: '请求流量',
        trafficResponse: '响应流量',
        bandwidthTotal: '总带宽',
        bandwidthRequest: '请求带宽',
        bandwidthResponse: '响应带宽',
        originPullAnalysis: '回源分析',
        originPullRequests: '回源请求数',
        originPullTraffic: '回源流量',
        originPullBandwidth: '回源带宽',
        originPullTrend: '回源趋势',
        originPullTotal: '总回源流量',
        originPullRequest: '回源请求流量',
        originPullResponse: '回源响应流量',
        originPullRequestTraffic: '回源请求流量',
        originPullRequestCount: '回源请求数',
        originPullRequestBandwidth: '回源请求带宽峰值',
        originPullResponseTraffic: '回源响应流量',
        originPullResponseBandwidth: '回源响应带宽峰值',
        requestsAndPerformance: '请求与性能',
        avgResponseTime: '平均响应耗时',
        avgFirstByteTime: '平均首字节耗时',
        requestsTrend: '请求数趋势',
        responseTimeTrend: '响应耗时趋势',
        securityAnalysis: '安全分析',
        topAnalysis: 'TOP 分析',
        ccRateIntercepts: '速率限制拦截',
        ccAclIntercepts: 'ACL 拦截',
        ccManageIntercepts: '管理拦截',
        securityTrend: '安全拦截趋势',
        noOriginPullData: '暂无回源数据',
        noOriginPullDataDesc: '该站点在选定时间段内没有回源请求',
        backendNotStarted: '后端服务未启动',
        backendNotStartedDesc: '请启动后端服务以查看统一视图数据',
        noSecurityData: '暂无安全数据',
        noSecurityDataDesc: '该站点在选定时间段内没有安全拦截记录',
        maxQueryRangeError: '时间范围不能超过 31 天',
        invalidDateRange: '结束时间必须晚于开始时间',
        autoGranularity: '自动',
        '5minGranularity': '5分钟',
        hourGranularity: '小时',
        dayGranularity: '天',
        selectGranularity: '时间粒度',
        timeGranularity: '时间粒度',
        minutes: '分钟',
        hourly: '小时',
        daily: '天',
        backgroundSettings: '背景设置',
        enableBackground: '启用背景',
        backgroundImage: '背景图片',
        uploadImage: '上传图片',
        imageUrlPlaceholder: '图片 URL',
        opacity: '透明度',
        blur: '模糊度',
        reset: '重置',
        themeColorSettings: '主题色设置',
        syncColors: '同步两种模式',
        lightModeColor: '浅色模式',
        darkModeColor: '深色模式',
        custom: '自定义',
        currentPreview: '当前预览',
        light: '浅色',
        dark: '深色'
      },
      en: {
        dashboardTitle: 'Unified Monitor Dashboard',
        loading: 'Loading...',
        loadError: 'Failed to load data',
        retry: 'Retry',
        noData: 'No data available',
        cloudflare: 'Cloudflare',
        edgeone: 'EdgeOne',
        unified: 'Unified View',
        totalRequests: 'Total Requests',
        totalTraffic: 'Total Traffic',
        totalBandwidth: 'Total Bandwidth',
        totalThreats: 'Total Threats',
        cachedRequests: 'Cached Requests',
        cachedBytes: 'Cached Bytes',
        cacheHitRate: 'Cache Hit Rate',
        geography: 'Geography',
        traffic: 'Traffic',
        bandwidth: 'Bandwidth',
        originPull: 'Origin Pull',
        requests: 'Requests',
        bytes: 'Bytes',
        threats: 'Threats',
        country: 'Country/Region',
        last24Hours: 'Last 24 Hours',
        last7Days: 'Last 7 Days',
        last30Days: 'Last 30 Days',
        period: 'Period',
        account: 'Account',
        zone: 'Zone',
        platform: 'Platform',
        autoRefresh: 'Auto Refresh',
        refresh: 'Refresh',
        customRange: 'Custom Range',
        apply: 'Apply',
        topUrls: 'Top URLs',
        topReferers: 'Top Referers',
        topBrowsers: 'Top Browsers',
        topOS: 'Top OS',
        count: 'Requests',
        ratio: 'Ratio',
        item: 'Item',
        topDevices: 'Top Devices',
        statusCodeDistribution: 'Status Code Distribution',
        securityStats: 'Security Statistics',
        intercepts: 'Intercepts',
        edgeFunctions: 'Edge Functions',
        functionRequests: 'Function Requests',
        cpuTime: 'CPU Time',
        trafficAnalysis: 'Traffic Analysis',
        bandwidthAnalysis: 'Bandwidth Analysis',
        clientRequestTraffic: 'Client Request Traffic',
        responseTraffic: 'Response Traffic',
        peakBandwidth: 'Peak Bandwidth',
        peakRequestBandwidth: 'Peak Request Bandwidth',
        peakResponseBandwidth: 'Peak Response Bandwidth',
        clientRequests: 'Client Requests',
        response: 'Response',
        trafficTotal: 'Total Traffic',
        trafficRequest: 'Request Traffic',
        trafficResponse: 'Response Traffic',
        bandwidthTotal: 'Total Bandwidth',
        bandwidthRequest: 'Request Bandwidth',
        bandwidthResponse: 'Response Bandwidth',
        originPullAnalysis: 'Origin Pull Analysis',
        originPullRequests: 'Origin Pull Requests',
        originPullTraffic: 'Origin Pull Traffic',
        originPullBandwidth: 'Origin Pull Bandwidth',
        originPullTrend: 'Origin Pull Trend',
        originPullTotal: 'Total Origin Pull',
        originPullRequest: 'Origin Pull Request Traffic',
        originPullResponse: 'Origin Pull Response Traffic',
        originPullRequestTraffic: 'Origin Pull Request Traffic',
        originPullRequestCount: 'Origin Pull Request Count',
        originPullRequestBandwidth: 'Origin Pull Request Bandwidth Peak',
        originPullResponseTraffic: 'Origin Pull Response Traffic',
        originPullResponseBandwidth: 'Origin Pull Response Bandwidth Peak',
        requestsAndPerformance: 'Requests & Performance',
        avgResponseTime: 'Avg Response Time',
        avgFirstByteTime: 'Avg First Byte Time',
        requestsTrend: 'Requests Trend',
        responseTimeTrend: 'Response Time Trend',
        securityAnalysis: 'Security Analysis',
        topAnalysis: 'Top Analysis',
        ccRateIntercepts: 'Rate Limit Intercepts',
        ccAclIntercepts: 'ACL Intercepts',
        ccManageIntercepts: 'Manage Intercepts',
        securityTrend: 'Security Intercept Trend',
        noOriginPullData: 'No Origin Pull Data',
        noOriginPullDataDesc: 'No origin pull requests for this zone in the selected period',
        backendNotStarted: 'Backend Service Not Started',
        backendNotStartedDesc: 'Please start the backend service to view unified dashboard data',
        noSecurityData: 'No Security Data',
        noSecurityDataDesc: 'No security intercept records for this zone in the selected period',
        maxQueryRangeError: 'Time range cannot exceed 31 days',
        invalidDateRange: 'End time must be later than start time',
        autoGranularity: 'Auto',
        '5minGranularity': '5 Min',
        hourGranularity: 'Hour',
        dayGranularity: 'Day',
        selectGranularity: 'Granularity',
        timeGranularity: 'Time Granularity',
        minutes: 'min',
        hourly: 'Hour',
        daily: 'Day',
        backgroundSettings: 'Background Settings',
        enableBackground: 'Enable Background',
        backgroundImage: 'Background Image',
        uploadImage: 'Upload Image',
        imageUrlPlaceholder: 'Image URL',
        opacity: 'Opacity',
        blur: 'Blur',
        reset: 'Reset',
        themeColorSettings: 'Theme Color',
        syncColors: 'Sync Both Modes',
        lightModeColor: 'Light Mode',
        darkModeColor: 'Dark Mode',
        custom: 'Custom',
        currentPreview: 'Current Preview',
        light: 'Light',
        dark: 'Dark'
      }
    };

    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
